server:
  port: 9001
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
turbine:
  app-config: service-consumer
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  instanceUrlSuffix:
      default: actuator/hystrix.stream