server:
  port: 9000
  servlet:
    context-path: /api

spring:
  application:
    name: template-api

  main:
    allow-bean-definition-overriding: true

#日志配置
logging:
  config: classpath:logConfig/log4j2-dev.xml

