server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: template-api

  main:
    allow-bean-definition-overriding: true

  cloud:
    #nacos注册配置中心
    nacos:
      discovery:
        server-addr: localhost:8848
        group: tonytaotao

#日志配置
logging:
  config: classpath:logConfig/log4j2-dev.xml

